import type { Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Host_Grotesk } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
const font =Host_Grotesk({
  subsets:['latin', 'latin-ext']
})
export const metadata: Metadata = {
  title: 'Vision ai',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${font.className} w-full h-screen overflow-hidden antialiased`}>
          <Toaster/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}